/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authPagesRouteRouteImport } from './routes/(auth-pages)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation/$invitationId'
import { Route as authPagesSignupRouteImport } from './routes/(auth-pages)/signup'
import { Route as authPagesLoginRouteImport } from './routes/(auth-pages)/login'
import { Route as SubdomainSlugRouteRouteImport } from './routes/subdomain/$slug/route'
import { Route as authenticatedDashboardRouteRouteImport } from './routes/(authenticated)/dashboard/route'
import { Route as SubdomainSlugIndexRouteImport } from './routes/subdomain/$slug/index'
import { Route as authenticatedDashboardIndexRouteImport } from './routes/(authenticated)/dashboard/index'
import { Route as SubdomainSlugRoadmapRouteImport } from './routes/subdomain/$slug/roadmap'
import { Route as SubdomainSlugChangelogRouteImport } from './routes/subdomain/$slug/changelog'
import { Route as SubdomainSlugDotwellKnownRouteImport } from './routes/subdomain/$slug/[.]well-known'
import { Route as SubdomainSlugIdeaIdRouteImport } from './routes/subdomain/$slug/$ideaId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatedDashboardOrgSlugRouteRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/route'
import { Route as authenticatedDashboardOrgSlugIndexRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/index'
import { Route as authenticatedDashboardOrgSlugSettingsIndexRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/settings/index'
import { Route as authenticatedDashboardOrgSlugRoadmapIndexRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/roadmap/index'
import { Route as authenticatedDashboardOrgSlugMembersIndexRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/members/index'
import { Route as authenticatedDashboardOrgSlugIdeasIndexRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/ideas/index'
import { Route as authenticatedDashboardOrgSlugChangelogIndexRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/changelog/index'
import { Route as authenticatedDashboardOrgSlugAccountIndexRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/account/index'
import { Route as SubdomainSlugApiAuthSplatRouteImport } from './routes/subdomain/$slug/api/auth/$'
import { Route as authenticatedDashboardOrgSlugIdeasIdeaIdRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/ideas/$ideaId'
import { Route as authenticatedDashboardOrgSlugChangelogNewRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/changelog/new'
import { Route as authenticatedDashboardOrgSlugChangelogChangelogIdRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/changelog/$changelogId'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesRouteRoute = authPagesRouteRouteImport.update({
  id: '/(auth-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const authPagesSignupRoute = authPagesSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const SubdomainSlugRouteRoute = SubdomainSlugRouteRouteImport.update({
  id: '/subdomain/$slug',
  path: '/subdomain/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedDashboardRouteRoute =
  authenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const SubdomainSlugIndexRoute = SubdomainSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubdomainSlugRouteRoute,
} as any)
const authenticatedDashboardIndexRoute =
  authenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const SubdomainSlugRoadmapRoute = SubdomainSlugRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => SubdomainSlugRouteRoute,
} as any)
const SubdomainSlugChangelogRoute = SubdomainSlugChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => SubdomainSlugRouteRoute,
} as any)
const SubdomainSlugDotwellKnownRoute =
  SubdomainSlugDotwellKnownRouteImport.update({
    id: '/.well-known',
    path: '/.well-known',
    getParentRoute: () => SubdomainSlugRouteRoute,
  } as any)
const SubdomainSlugIdeaIdRoute = SubdomainSlugIdeaIdRouteImport.update({
  id: '/$ideaId',
  path: '/$ideaId',
  getParentRoute: () => SubdomainSlugRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedDashboardOrgSlugRouteRoute =
  authenticatedDashboardOrgSlugRouteRouteImport.update({
    id: '/$orgSlug',
    path: '/$orgSlug',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugIndexRoute =
  authenticatedDashboardOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugSettingsIndexRoute =
  authenticatedDashboardOrgSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugRoadmapIndexRoute =
  authenticatedDashboardOrgSlugRoadmapIndexRouteImport.update({
    id: '/roadmap/',
    path: '/roadmap/',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugMembersIndexRoute =
  authenticatedDashboardOrgSlugMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugIdeasIndexRoute =
  authenticatedDashboardOrgSlugIdeasIndexRouteImport.update({
    id: '/ideas/',
    path: '/ideas/',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugChangelogIndexRoute =
  authenticatedDashboardOrgSlugChangelogIndexRouteImport.update({
    id: '/changelog/',
    path: '/changelog/',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugAccountIndexRoute =
  authenticatedDashboardOrgSlugAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const SubdomainSlugApiAuthSplatRoute =
  SubdomainSlugApiAuthSplatRouteImport.update({
    id: '/api/auth/$',
    path: '/api/auth/$',
    getParentRoute: () => SubdomainSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugIdeasIdeaIdRoute =
  authenticatedDashboardOrgSlugIdeasIdeaIdRouteImport.update({
    id: '/ideas/$ideaId',
    path: '/ideas/$ideaId',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugChangelogNewRoute =
  authenticatedDashboardOrgSlugChangelogNewRouteImport.update({
    id: '/changelog/new',
    path: '/changelog/new',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugChangelogChangelogIdRoute =
  authenticatedDashboardOrgSlugChangelogChangelogIdRouteImport.update({
    id: '/changelog/$changelogId',
    path: '/changelog/$changelogId',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/subdomain/$slug': typeof SubdomainSlugRouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/dashboard/$orgSlug': typeof authenticatedDashboardOrgSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/subdomain/$slug/$ideaId': typeof SubdomainSlugIdeaIdRoute
  '/subdomain/$slug/.well-known': typeof SubdomainSlugDotwellKnownRoute
  '/subdomain/$slug/changelog': typeof SubdomainSlugChangelogRoute
  '/subdomain/$slug/roadmap': typeof SubdomainSlugRoadmapRoute
  '/dashboard/': typeof authenticatedDashboardIndexRoute
  '/subdomain/$slug/': typeof SubdomainSlugIndexRoute
  '/dashboard/$orgSlug/': typeof authenticatedDashboardOrgSlugIndexRoute
  '/dashboard/$orgSlug/changelog/$changelogId': typeof authenticatedDashboardOrgSlugChangelogChangelogIdRoute
  '/dashboard/$orgSlug/changelog/new': typeof authenticatedDashboardOrgSlugChangelogNewRoute
  '/dashboard/$orgSlug/ideas/$ideaId': typeof authenticatedDashboardOrgSlugIdeasIdeaIdRoute
  '/subdomain/$slug/api/auth/$': typeof SubdomainSlugApiAuthSplatRoute
  '/dashboard/$orgSlug/account/': typeof authenticatedDashboardOrgSlugAccountIndexRoute
  '/dashboard/$orgSlug/changelog/': typeof authenticatedDashboardOrgSlugChangelogIndexRoute
  '/dashboard/$orgSlug/ideas/': typeof authenticatedDashboardOrgSlugIdeasIndexRoute
  '/dashboard/$orgSlug/members/': typeof authenticatedDashboardOrgSlugMembersIndexRoute
  '/dashboard/$orgSlug/roadmap/': typeof authenticatedDashboardOrgSlugRoadmapIndexRoute
  '/dashboard/$orgSlug/settings/': typeof authenticatedDashboardOrgSlugSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/subdomain/$slug/$ideaId': typeof SubdomainSlugIdeaIdRoute
  '/subdomain/$slug/.well-known': typeof SubdomainSlugDotwellKnownRoute
  '/subdomain/$slug/changelog': typeof SubdomainSlugChangelogRoute
  '/subdomain/$slug/roadmap': typeof SubdomainSlugRoadmapRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
  '/subdomain/$slug': typeof SubdomainSlugIndexRoute
  '/dashboard/$orgSlug': typeof authenticatedDashboardOrgSlugIndexRoute
  '/dashboard/$orgSlug/changelog/$changelogId': typeof authenticatedDashboardOrgSlugChangelogChangelogIdRoute
  '/dashboard/$orgSlug/changelog/new': typeof authenticatedDashboardOrgSlugChangelogNewRoute
  '/dashboard/$orgSlug/ideas/$ideaId': typeof authenticatedDashboardOrgSlugIdeasIdeaIdRoute
  '/subdomain/$slug/api/auth/$': typeof SubdomainSlugApiAuthSplatRoute
  '/dashboard/$orgSlug/account': typeof authenticatedDashboardOrgSlugAccountIndexRoute
  '/dashboard/$orgSlug/changelog': typeof authenticatedDashboardOrgSlugChangelogIndexRoute
  '/dashboard/$orgSlug/ideas': typeof authenticatedDashboardOrgSlugIdeasIndexRoute
  '/dashboard/$orgSlug/members': typeof authenticatedDashboardOrgSlugMembersIndexRoute
  '/dashboard/$orgSlug/roadmap': typeof authenticatedDashboardOrgSlugRoadmapIndexRoute
  '/dashboard/$orgSlug/settings': typeof authenticatedDashboardOrgSlugSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth-pages)': typeof authPagesRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/subdomain/$slug': typeof SubdomainSlugRouteRouteWithChildren
  '/(auth-pages)/login': typeof authPagesLoginRoute
  '/(auth-pages)/signup': typeof authPagesSignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/(authenticated)/dashboard/$orgSlug': typeof authenticatedDashboardOrgSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/subdomain/$slug/$ideaId': typeof SubdomainSlugIdeaIdRoute
  '/subdomain/$slug/.well-known': typeof SubdomainSlugDotwellKnownRoute
  '/subdomain/$slug/changelog': typeof SubdomainSlugChangelogRoute
  '/subdomain/$slug/roadmap': typeof SubdomainSlugRoadmapRoute
  '/(authenticated)/dashboard/': typeof authenticatedDashboardIndexRoute
  '/subdomain/$slug/': typeof SubdomainSlugIndexRoute
  '/(authenticated)/dashboard/$orgSlug/': typeof authenticatedDashboardOrgSlugIndexRoute
  '/(authenticated)/dashboard/$orgSlug/changelog/$changelogId': typeof authenticatedDashboardOrgSlugChangelogChangelogIdRoute
  '/(authenticated)/dashboard/$orgSlug/changelog/new': typeof authenticatedDashboardOrgSlugChangelogNewRoute
  '/(authenticated)/dashboard/$orgSlug/ideas/$ideaId': typeof authenticatedDashboardOrgSlugIdeasIdeaIdRoute
  '/subdomain/$slug/api/auth/$': typeof SubdomainSlugApiAuthSplatRoute
  '/(authenticated)/dashboard/$orgSlug/account/': typeof authenticatedDashboardOrgSlugAccountIndexRoute
  '/(authenticated)/dashboard/$orgSlug/changelog/': typeof authenticatedDashboardOrgSlugChangelogIndexRoute
  '/(authenticated)/dashboard/$orgSlug/ideas/': typeof authenticatedDashboardOrgSlugIdeasIndexRoute
  '/(authenticated)/dashboard/$orgSlug/members/': typeof authenticatedDashboardOrgSlugMembersIndexRoute
  '/(authenticated)/dashboard/$orgSlug/roadmap/': typeof authenticatedDashboardOrgSlugRoadmapIndexRoute
  '/(authenticated)/dashboard/$orgSlug/settings/': typeof authenticatedDashboardOrgSlugSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/subdomain/$slug'
    | '/login'
    | '/signup'
    | '/accept-invitation/$invitationId'
    | '/dashboard/$orgSlug'
    | '/api/auth/$'
    | '/subdomain/$slug/$ideaId'
    | '/subdomain/$slug/.well-known'
    | '/subdomain/$slug/changelog'
    | '/subdomain/$slug/roadmap'
    | '/dashboard/'
    | '/subdomain/$slug/'
    | '/dashboard/$orgSlug/'
    | '/dashboard/$orgSlug/changelog/$changelogId'
    | '/dashboard/$orgSlug/changelog/new'
    | '/dashboard/$orgSlug/ideas/$ideaId'
    | '/subdomain/$slug/api/auth/$'
    | '/dashboard/$orgSlug/account/'
    | '/dashboard/$orgSlug/changelog/'
    | '/dashboard/$orgSlug/ideas/'
    | '/dashboard/$orgSlug/members/'
    | '/dashboard/$orgSlug/roadmap/'
    | '/dashboard/$orgSlug/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/accept-invitation/$invitationId'
    | '/api/auth/$'
    | '/subdomain/$slug/$ideaId'
    | '/subdomain/$slug/.well-known'
    | '/subdomain/$slug/changelog'
    | '/subdomain/$slug/roadmap'
    | '/dashboard'
    | '/subdomain/$slug'
    | '/dashboard/$orgSlug'
    | '/dashboard/$orgSlug/changelog/$changelogId'
    | '/dashboard/$orgSlug/changelog/new'
    | '/dashboard/$orgSlug/ideas/$ideaId'
    | '/subdomain/$slug/api/auth/$'
    | '/dashboard/$orgSlug/account'
    | '/dashboard/$orgSlug/changelog'
    | '/dashboard/$orgSlug/ideas'
    | '/dashboard/$orgSlug/members'
    | '/dashboard/$orgSlug/roadmap'
    | '/dashboard/$orgSlug/settings'
  id:
    | '__root__'
    | '/'
    | '/(auth-pages)'
    | '/(authenticated)'
    | '/(authenticated)/dashboard'
    | '/subdomain/$slug'
    | '/(auth-pages)/login'
    | '/(auth-pages)/signup'
    | '/accept-invitation/$invitationId'
    | '/(authenticated)/dashboard/$orgSlug'
    | '/api/auth/$'
    | '/subdomain/$slug/$ideaId'
    | '/subdomain/$slug/.well-known'
    | '/subdomain/$slug/changelog'
    | '/subdomain/$slug/roadmap'
    | '/(authenticated)/dashboard/'
    | '/subdomain/$slug/'
    | '/(authenticated)/dashboard/$orgSlug/'
    | '/(authenticated)/dashboard/$orgSlug/changelog/$changelogId'
    | '/(authenticated)/dashboard/$orgSlug/changelog/new'
    | '/(authenticated)/dashboard/$orgSlug/ideas/$ideaId'
    | '/subdomain/$slug/api/auth/$'
    | '/(authenticated)/dashboard/$orgSlug/account/'
    | '/(authenticated)/dashboard/$orgSlug/changelog/'
    | '/(authenticated)/dashboard/$orgSlug/ideas/'
    | '/(authenticated)/dashboard/$orgSlug/members/'
    | '/(authenticated)/dashboard/$orgSlug/roadmap/'
    | '/(authenticated)/dashboard/$orgSlug/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authPagesRouteRoute: typeof authPagesRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  SubdomainSlugRouteRoute: typeof SubdomainSlugRouteRouteWithChildren
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)': {
      id: '/(auth-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)/signup': {
      id: '/(auth-pages)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authPagesSignupRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/login': {
      id: '/(auth-pages)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/subdomain/$slug': {
      id: '/subdomain/$slug'
      path: '/subdomain/$slug'
      fullPath: '/subdomain/$slug'
      preLoaderRoute: typeof SubdomainSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/subdomain/$slug/': {
      id: '/subdomain/$slug/'
      path: '/'
      fullPath: '/subdomain/$slug/'
      preLoaderRoute: typeof SubdomainSlugIndexRouteImport
      parentRoute: typeof SubdomainSlugRouteRoute
    }
    '/(authenticated)/dashboard/': {
      id: '/(authenticated)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedDashboardIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/subdomain/$slug/roadmap': {
      id: '/subdomain/$slug/roadmap'
      path: '/roadmap'
      fullPath: '/subdomain/$slug/roadmap'
      preLoaderRoute: typeof SubdomainSlugRoadmapRouteImport
      parentRoute: typeof SubdomainSlugRouteRoute
    }
    '/subdomain/$slug/changelog': {
      id: '/subdomain/$slug/changelog'
      path: '/changelog'
      fullPath: '/subdomain/$slug/changelog'
      preLoaderRoute: typeof SubdomainSlugChangelogRouteImport
      parentRoute: typeof SubdomainSlugRouteRoute
    }
    '/subdomain/$slug/.well-known': {
      id: '/subdomain/$slug/.well-known'
      path: '/.well-known'
      fullPath: '/subdomain/$slug/.well-known'
      preLoaderRoute: typeof SubdomainSlugDotwellKnownRouteImport
      parentRoute: typeof SubdomainSlugRouteRoute
    }
    '/subdomain/$slug/$ideaId': {
      id: '/subdomain/$slug/$ideaId'
      path: '/$ideaId'
      fullPath: '/subdomain/$slug/$ideaId'
      preLoaderRoute: typeof SubdomainSlugIdeaIdRouteImport
      parentRoute: typeof SubdomainSlugRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard/$orgSlug': {
      id: '/(authenticated)/dashboard/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/dashboard/$orgSlug'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugRouteRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/': {
      id: '/(authenticated)/dashboard/$orgSlug/'
      path: '/'
      fullPath: '/dashboard/$orgSlug/'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugIndexRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/settings/': {
      id: '/(authenticated)/dashboard/$orgSlug/settings/'
      path: '/settings'
      fullPath: '/dashboard/$orgSlug/settings/'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugSettingsIndexRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/roadmap/': {
      id: '/(authenticated)/dashboard/$orgSlug/roadmap/'
      path: '/roadmap'
      fullPath: '/dashboard/$orgSlug/roadmap/'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugRoadmapIndexRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/members/': {
      id: '/(authenticated)/dashboard/$orgSlug/members/'
      path: '/members'
      fullPath: '/dashboard/$orgSlug/members/'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugMembersIndexRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/ideas/': {
      id: '/(authenticated)/dashboard/$orgSlug/ideas/'
      path: '/ideas'
      fullPath: '/dashboard/$orgSlug/ideas/'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugIdeasIndexRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/changelog/': {
      id: '/(authenticated)/dashboard/$orgSlug/changelog/'
      path: '/changelog'
      fullPath: '/dashboard/$orgSlug/changelog/'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugChangelogIndexRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/account/': {
      id: '/(authenticated)/dashboard/$orgSlug/account/'
      path: '/account'
      fullPath: '/dashboard/$orgSlug/account/'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugAccountIndexRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/subdomain/$slug/api/auth/$': {
      id: '/subdomain/$slug/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/subdomain/$slug/api/auth/$'
      preLoaderRoute: typeof SubdomainSlugApiAuthSplatRouteImport
      parentRoute: typeof SubdomainSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/ideas/$ideaId': {
      id: '/(authenticated)/dashboard/$orgSlug/ideas/$ideaId'
      path: '/ideas/$ideaId'
      fullPath: '/dashboard/$orgSlug/ideas/$ideaId'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugIdeasIdeaIdRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/changelog/new': {
      id: '/(authenticated)/dashboard/$orgSlug/changelog/new'
      path: '/changelog/new'
      fullPath: '/dashboard/$orgSlug/changelog/new'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugChangelogNewRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/changelog/$changelogId': {
      id: '/(authenticated)/dashboard/$orgSlug/changelog/$changelogId'
      path: '/changelog/$changelogId'
      fullPath: '/dashboard/$orgSlug/changelog/$changelogId'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugChangelogChangelogIdRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
  }
}

interface authPagesRouteRouteChildren {
  authPagesLoginRoute: typeof authPagesLoginRoute
  authPagesSignupRoute: typeof authPagesSignupRoute
}

const authPagesRouteRouteChildren: authPagesRouteRouteChildren = {
  authPagesLoginRoute: authPagesLoginRoute,
  authPagesSignupRoute: authPagesSignupRoute,
}

const authPagesRouteRouteWithChildren = authPagesRouteRoute._addFileChildren(
  authPagesRouteRouteChildren,
)

interface authenticatedDashboardOrgSlugRouteRouteChildren {
  authenticatedDashboardOrgSlugIndexRoute: typeof authenticatedDashboardOrgSlugIndexRoute
  authenticatedDashboardOrgSlugChangelogChangelogIdRoute: typeof authenticatedDashboardOrgSlugChangelogChangelogIdRoute
  authenticatedDashboardOrgSlugChangelogNewRoute: typeof authenticatedDashboardOrgSlugChangelogNewRoute
  authenticatedDashboardOrgSlugIdeasIdeaIdRoute: typeof authenticatedDashboardOrgSlugIdeasIdeaIdRoute
  authenticatedDashboardOrgSlugAccountIndexRoute: typeof authenticatedDashboardOrgSlugAccountIndexRoute
  authenticatedDashboardOrgSlugChangelogIndexRoute: typeof authenticatedDashboardOrgSlugChangelogIndexRoute
  authenticatedDashboardOrgSlugIdeasIndexRoute: typeof authenticatedDashboardOrgSlugIdeasIndexRoute
  authenticatedDashboardOrgSlugMembersIndexRoute: typeof authenticatedDashboardOrgSlugMembersIndexRoute
  authenticatedDashboardOrgSlugRoadmapIndexRoute: typeof authenticatedDashboardOrgSlugRoadmapIndexRoute
  authenticatedDashboardOrgSlugSettingsIndexRoute: typeof authenticatedDashboardOrgSlugSettingsIndexRoute
}

const authenticatedDashboardOrgSlugRouteRouteChildren: authenticatedDashboardOrgSlugRouteRouteChildren =
  {
    authenticatedDashboardOrgSlugIndexRoute:
      authenticatedDashboardOrgSlugIndexRoute,
    authenticatedDashboardOrgSlugChangelogChangelogIdRoute:
      authenticatedDashboardOrgSlugChangelogChangelogIdRoute,
    authenticatedDashboardOrgSlugChangelogNewRoute:
      authenticatedDashboardOrgSlugChangelogNewRoute,
    authenticatedDashboardOrgSlugIdeasIdeaIdRoute:
      authenticatedDashboardOrgSlugIdeasIdeaIdRoute,
    authenticatedDashboardOrgSlugAccountIndexRoute:
      authenticatedDashboardOrgSlugAccountIndexRoute,
    authenticatedDashboardOrgSlugChangelogIndexRoute:
      authenticatedDashboardOrgSlugChangelogIndexRoute,
    authenticatedDashboardOrgSlugIdeasIndexRoute:
      authenticatedDashboardOrgSlugIdeasIndexRoute,
    authenticatedDashboardOrgSlugMembersIndexRoute:
      authenticatedDashboardOrgSlugMembersIndexRoute,
    authenticatedDashboardOrgSlugRoadmapIndexRoute:
      authenticatedDashboardOrgSlugRoadmapIndexRoute,
    authenticatedDashboardOrgSlugSettingsIndexRoute:
      authenticatedDashboardOrgSlugSettingsIndexRoute,
  }

const authenticatedDashboardOrgSlugRouteRouteWithChildren =
  authenticatedDashboardOrgSlugRouteRoute._addFileChildren(
    authenticatedDashboardOrgSlugRouteRouteChildren,
  )

interface authenticatedDashboardRouteRouteChildren {
  authenticatedDashboardOrgSlugRouteRoute: typeof authenticatedDashboardOrgSlugRouteRouteWithChildren
  authenticatedDashboardIndexRoute: typeof authenticatedDashboardIndexRoute
}

const authenticatedDashboardRouteRouteChildren: authenticatedDashboardRouteRouteChildren =
  {
    authenticatedDashboardOrgSlugRouteRoute:
      authenticatedDashboardOrgSlugRouteRouteWithChildren,
    authenticatedDashboardIndexRoute: authenticatedDashboardIndexRoute,
  }

const authenticatedDashboardRouteRouteWithChildren =
  authenticatedDashboardRouteRoute._addFileChildren(
    authenticatedDashboardRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedDashboardRouteRoute: typeof authenticatedDashboardRouteRouteWithChildren
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardRouteRoute:
    authenticatedDashboardRouteRouteWithChildren,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface SubdomainSlugRouteRouteChildren {
  SubdomainSlugIdeaIdRoute: typeof SubdomainSlugIdeaIdRoute
  SubdomainSlugDotwellKnownRoute: typeof SubdomainSlugDotwellKnownRoute
  SubdomainSlugChangelogRoute: typeof SubdomainSlugChangelogRoute
  SubdomainSlugRoadmapRoute: typeof SubdomainSlugRoadmapRoute
  SubdomainSlugIndexRoute: typeof SubdomainSlugIndexRoute
  SubdomainSlugApiAuthSplatRoute: typeof SubdomainSlugApiAuthSplatRoute
}

const SubdomainSlugRouteRouteChildren: SubdomainSlugRouteRouteChildren = {
  SubdomainSlugIdeaIdRoute: SubdomainSlugIdeaIdRoute,
  SubdomainSlugDotwellKnownRoute: SubdomainSlugDotwellKnownRoute,
  SubdomainSlugChangelogRoute: SubdomainSlugChangelogRoute,
  SubdomainSlugRoadmapRoute: SubdomainSlugRoadmapRoute,
  SubdomainSlugIndexRoute: SubdomainSlugIndexRoute,
  SubdomainSlugApiAuthSplatRoute: SubdomainSlugApiAuthSplatRoute,
}

const SubdomainSlugRouteRouteWithChildren =
  SubdomainSlugRouteRoute._addFileChildren(SubdomainSlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authPagesRouteRoute: authPagesRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  SubdomainSlugRouteRoute: SubdomainSlugRouteRouteWithChildren,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
