/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authPagesRouteRouteImport } from './routes/(auth-pages)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation/$invitationId'
import { Route as authPagesSignupRouteImport } from './routes/(auth-pages)/signup'
import { Route as authPagesLoginRouteImport } from './routes/(auth-pages)/login'
import { Route as OrgSlugRouteRouteImport } from './routes/org/$slug/route'
import { Route as authenticatedDashboardRouteRouteImport } from './routes/(authenticated)/dashboard/route'
import { Route as OrgSlugIndexRouteImport } from './routes/org/$slug/index'
import { Route as authenticatedDashboardIndexRouteImport } from './routes/(authenticated)/dashboard/index'
import { Route as OrgSlugRoadmapRouteImport } from './routes/org/$slug/roadmap'
import { Route as OrgSlugChangelogRouteImport } from './routes/org/$slug/changelog'
import { Route as OrgSlugIdeaIdRouteImport } from './routes/org/$slug/$ideaId'
import { Route as ApiWidgetOrganizationRouteImport } from './routes/api/widget/organization'
import { Route as ApiWidgetIdeasRouteImport } from './routes/api/widget/ideas'
import { Route as ApiWidgetChangelogRouteImport } from './routes/api/widget/changelog'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatedDashboardOrgSlugRouteRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/route'
import { Route as authenticatedDashboardOrgSlugIndexRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/index'
import { Route as ApiZapierWebhooksSubscribeRouteImport } from './routes/api/zapier/webhooks/subscribe'
import { Route as authenticatedDashboardOrgSlugSettingsIndexRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/settings/index'
import { Route as authenticatedDashboardOrgSlugRoadmapIndexRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/roadmap/index'
import { Route as authenticatedDashboardOrgSlugMembersIndexRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/members/index'
import { Route as authenticatedDashboardOrgSlugIdeasIndexRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/ideas/index'
import { Route as authenticatedDashboardOrgSlugChangelogIndexRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/changelog/index'
import { Route as authenticatedDashboardOrgSlugAccountIndexRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/account/index'
import { Route as ApiZapierWebhooksSubscribeIdRouteImport } from './routes/api/zapier/webhooks/subscribe/$id'
import { Route as authenticatedDashboardOrgSlugIdeasIdeaIdRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/ideas/$ideaId'
import { Route as authenticatedDashboardOrgSlugChangelogNewRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/changelog/new'
import { Route as authenticatedDashboardOrgSlugChangelogChangelogIdRouteImport } from './routes/(authenticated)/dashboard/$orgSlug/changelog/$changelogId'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesRouteRoute = authPagesRouteRouteImport.update({
  id: '/(auth-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const authPagesSignupRoute = authPagesSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const OrgSlugRouteRoute = OrgSlugRouteRouteImport.update({
  id: '/org/$slug',
  path: '/org/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedDashboardRouteRoute =
  authenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const authenticatedDashboardIndexRoute =
  authenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const OrgSlugRoadmapRoute = OrgSlugRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugChangelogRoute = OrgSlugChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugIdeaIdRoute = OrgSlugIdeaIdRouteImport.update({
  id: '/$ideaId',
  path: '/$ideaId',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const ApiWidgetOrganizationRoute = ApiWidgetOrganizationRouteImport.update({
  id: '/api/widget/organization',
  path: '/api/widget/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidgetIdeasRoute = ApiWidgetIdeasRouteImport.update({
  id: '/api/widget/ideas',
  path: '/api/widget/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidgetChangelogRoute = ApiWidgetChangelogRouteImport.update({
  id: '/api/widget/changelog',
  path: '/api/widget/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedDashboardOrgSlugRouteRoute =
  authenticatedDashboardOrgSlugRouteRouteImport.update({
    id: '/$orgSlug',
    path: '/$orgSlug',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugIndexRoute =
  authenticatedDashboardOrgSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const ApiZapierWebhooksSubscribeRoute =
  ApiZapierWebhooksSubscribeRouteImport.update({
    id: '/api/zapier/webhooks/subscribe',
    path: '/api/zapier/webhooks/subscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const authenticatedDashboardOrgSlugSettingsIndexRoute =
  authenticatedDashboardOrgSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugRoadmapIndexRoute =
  authenticatedDashboardOrgSlugRoadmapIndexRouteImport.update({
    id: '/roadmap/',
    path: '/roadmap/',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugMembersIndexRoute =
  authenticatedDashboardOrgSlugMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugIdeasIndexRoute =
  authenticatedDashboardOrgSlugIdeasIndexRouteImport.update({
    id: '/ideas/',
    path: '/ideas/',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugChangelogIndexRoute =
  authenticatedDashboardOrgSlugChangelogIndexRouteImport.update({
    id: '/changelog/',
    path: '/changelog/',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugAccountIndexRoute =
  authenticatedDashboardOrgSlugAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const ApiZapierWebhooksSubscribeIdRoute =
  ApiZapierWebhooksSubscribeIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiZapierWebhooksSubscribeRoute,
  } as any)
const authenticatedDashboardOrgSlugIdeasIdeaIdRoute =
  authenticatedDashboardOrgSlugIdeasIdeaIdRouteImport.update({
    id: '/ideas/$ideaId',
    path: '/ideas/$ideaId',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugChangelogNewRoute =
  authenticatedDashboardOrgSlugChangelogNewRouteImport.update({
    id: '/changelog/new',
    path: '/changelog/new',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)
const authenticatedDashboardOrgSlugChangelogChangelogIdRoute =
  authenticatedDashboardOrgSlugChangelogChangelogIdRouteImport.update({
    id: '/changelog/$changelogId',
    path: '/changelog/$changelogId',
    getParentRoute: () => authenticatedDashboardOrgSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/org/$slug': typeof OrgSlugRouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/api/upload': typeof ApiUploadRoute
  '/dashboard/$orgSlug': typeof authenticatedDashboardOrgSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/widget/changelog': typeof ApiWidgetChangelogRoute
  '/api/widget/ideas': typeof ApiWidgetIdeasRoute
  '/api/widget/organization': typeof ApiWidgetOrganizationRoute
  '/org/$slug/$ideaId': typeof OrgSlugIdeaIdRoute
  '/org/$slug/changelog': typeof OrgSlugChangelogRoute
  '/org/$slug/roadmap': typeof OrgSlugRoadmapRoute
  '/dashboard/': typeof authenticatedDashboardIndexRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/api/zapier/webhooks/subscribe': typeof ApiZapierWebhooksSubscribeRouteWithChildren
  '/dashboard/$orgSlug/': typeof authenticatedDashboardOrgSlugIndexRoute
  '/dashboard/$orgSlug/changelog/$changelogId': typeof authenticatedDashboardOrgSlugChangelogChangelogIdRoute
  '/dashboard/$orgSlug/changelog/new': typeof authenticatedDashboardOrgSlugChangelogNewRoute
  '/dashboard/$orgSlug/ideas/$ideaId': typeof authenticatedDashboardOrgSlugIdeasIdeaIdRoute
  '/api/zapier/webhooks/subscribe/$id': typeof ApiZapierWebhooksSubscribeIdRoute
  '/dashboard/$orgSlug/account': typeof authenticatedDashboardOrgSlugAccountIndexRoute
  '/dashboard/$orgSlug/changelog': typeof authenticatedDashboardOrgSlugChangelogIndexRoute
  '/dashboard/$orgSlug/ideas': typeof authenticatedDashboardOrgSlugIdeasIndexRoute
  '/dashboard/$orgSlug/members': typeof authenticatedDashboardOrgSlugMembersIndexRoute
  '/dashboard/$orgSlug/roadmap': typeof authenticatedDashboardOrgSlugRoadmapIndexRoute
  '/dashboard/$orgSlug/settings': typeof authenticatedDashboardOrgSlugSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/widget/changelog': typeof ApiWidgetChangelogRoute
  '/api/widget/ideas': typeof ApiWidgetIdeasRoute
  '/api/widget/organization': typeof ApiWidgetOrganizationRoute
  '/org/$slug/$ideaId': typeof OrgSlugIdeaIdRoute
  '/org/$slug/changelog': typeof OrgSlugChangelogRoute
  '/org/$slug/roadmap': typeof OrgSlugRoadmapRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
  '/org/$slug': typeof OrgSlugIndexRoute
  '/api/zapier/webhooks/subscribe': typeof ApiZapierWebhooksSubscribeRouteWithChildren
  '/dashboard/$orgSlug': typeof authenticatedDashboardOrgSlugIndexRoute
  '/dashboard/$orgSlug/changelog/$changelogId': typeof authenticatedDashboardOrgSlugChangelogChangelogIdRoute
  '/dashboard/$orgSlug/changelog/new': typeof authenticatedDashboardOrgSlugChangelogNewRoute
  '/dashboard/$orgSlug/ideas/$ideaId': typeof authenticatedDashboardOrgSlugIdeasIdeaIdRoute
  '/api/zapier/webhooks/subscribe/$id': typeof ApiZapierWebhooksSubscribeIdRoute
  '/dashboard/$orgSlug/account': typeof authenticatedDashboardOrgSlugAccountIndexRoute
  '/dashboard/$orgSlug/changelog': typeof authenticatedDashboardOrgSlugChangelogIndexRoute
  '/dashboard/$orgSlug/ideas': typeof authenticatedDashboardOrgSlugIdeasIndexRoute
  '/dashboard/$orgSlug/members': typeof authenticatedDashboardOrgSlugMembersIndexRoute
  '/dashboard/$orgSlug/roadmap': typeof authenticatedDashboardOrgSlugRoadmapIndexRoute
  '/dashboard/$orgSlug/settings': typeof authenticatedDashboardOrgSlugSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth-pages)': typeof authPagesRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/org/$slug': typeof OrgSlugRouteRouteWithChildren
  '/(auth-pages)/login': typeof authPagesLoginRoute
  '/(auth-pages)/signup': typeof authPagesSignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/api/upload': typeof ApiUploadRoute
  '/(authenticated)/dashboard/$orgSlug': typeof authenticatedDashboardOrgSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/widget/changelog': typeof ApiWidgetChangelogRoute
  '/api/widget/ideas': typeof ApiWidgetIdeasRoute
  '/api/widget/organization': typeof ApiWidgetOrganizationRoute
  '/org/$slug/$ideaId': typeof OrgSlugIdeaIdRoute
  '/org/$slug/changelog': typeof OrgSlugChangelogRoute
  '/org/$slug/roadmap': typeof OrgSlugRoadmapRoute
  '/(authenticated)/dashboard/': typeof authenticatedDashboardIndexRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/api/zapier/webhooks/subscribe': typeof ApiZapierWebhooksSubscribeRouteWithChildren
  '/(authenticated)/dashboard/$orgSlug/': typeof authenticatedDashboardOrgSlugIndexRoute
  '/(authenticated)/dashboard/$orgSlug/changelog/$changelogId': typeof authenticatedDashboardOrgSlugChangelogChangelogIdRoute
  '/(authenticated)/dashboard/$orgSlug/changelog/new': typeof authenticatedDashboardOrgSlugChangelogNewRoute
  '/(authenticated)/dashboard/$orgSlug/ideas/$ideaId': typeof authenticatedDashboardOrgSlugIdeasIdeaIdRoute
  '/api/zapier/webhooks/subscribe/$id': typeof ApiZapierWebhooksSubscribeIdRoute
  '/(authenticated)/dashboard/$orgSlug/account/': typeof authenticatedDashboardOrgSlugAccountIndexRoute
  '/(authenticated)/dashboard/$orgSlug/changelog/': typeof authenticatedDashboardOrgSlugChangelogIndexRoute
  '/(authenticated)/dashboard/$orgSlug/ideas/': typeof authenticatedDashboardOrgSlugIdeasIndexRoute
  '/(authenticated)/dashboard/$orgSlug/members/': typeof authenticatedDashboardOrgSlugMembersIndexRoute
  '/(authenticated)/dashboard/$orgSlug/roadmap/': typeof authenticatedDashboardOrgSlugRoadmapIndexRoute
  '/(authenticated)/dashboard/$orgSlug/settings/': typeof authenticatedDashboardOrgSlugSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/org/$slug'
    | '/login'
    | '/signup'
    | '/accept-invitation/$invitationId'
    | '/api/upload'
    | '/dashboard/$orgSlug'
    | '/api/auth/$'
    | '/api/widget/changelog'
    | '/api/widget/ideas'
    | '/api/widget/organization'
    | '/org/$slug/$ideaId'
    | '/org/$slug/changelog'
    | '/org/$slug/roadmap'
    | '/dashboard/'
    | '/org/$slug/'
    | '/api/zapier/webhooks/subscribe'
    | '/dashboard/$orgSlug/'
    | '/dashboard/$orgSlug/changelog/$changelogId'
    | '/dashboard/$orgSlug/changelog/new'
    | '/dashboard/$orgSlug/ideas/$ideaId'
    | '/api/zapier/webhooks/subscribe/$id'
    | '/dashboard/$orgSlug/account'
    | '/dashboard/$orgSlug/changelog'
    | '/dashboard/$orgSlug/ideas'
    | '/dashboard/$orgSlug/members'
    | '/dashboard/$orgSlug/roadmap'
    | '/dashboard/$orgSlug/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/accept-invitation/$invitationId'
    | '/api/upload'
    | '/api/auth/$'
    | '/api/widget/changelog'
    | '/api/widget/ideas'
    | '/api/widget/organization'
    | '/org/$slug/$ideaId'
    | '/org/$slug/changelog'
    | '/org/$slug/roadmap'
    | '/dashboard'
    | '/org/$slug'
    | '/api/zapier/webhooks/subscribe'
    | '/dashboard/$orgSlug'
    | '/dashboard/$orgSlug/changelog/$changelogId'
    | '/dashboard/$orgSlug/changelog/new'
    | '/dashboard/$orgSlug/ideas/$ideaId'
    | '/api/zapier/webhooks/subscribe/$id'
    | '/dashboard/$orgSlug/account'
    | '/dashboard/$orgSlug/changelog'
    | '/dashboard/$orgSlug/ideas'
    | '/dashboard/$orgSlug/members'
    | '/dashboard/$orgSlug/roadmap'
    | '/dashboard/$orgSlug/settings'
  id:
    | '__root__'
    | '/'
    | '/(auth-pages)'
    | '/(authenticated)'
    | '/(authenticated)/dashboard'
    | '/org/$slug'
    | '/(auth-pages)/login'
    | '/(auth-pages)/signup'
    | '/accept-invitation/$invitationId'
    | '/api/upload'
    | '/(authenticated)/dashboard/$orgSlug'
    | '/api/auth/$'
    | '/api/widget/changelog'
    | '/api/widget/ideas'
    | '/api/widget/organization'
    | '/org/$slug/$ideaId'
    | '/org/$slug/changelog'
    | '/org/$slug/roadmap'
    | '/(authenticated)/dashboard/'
    | '/org/$slug/'
    | '/api/zapier/webhooks/subscribe'
    | '/(authenticated)/dashboard/$orgSlug/'
    | '/(authenticated)/dashboard/$orgSlug/changelog/$changelogId'
    | '/(authenticated)/dashboard/$orgSlug/changelog/new'
    | '/(authenticated)/dashboard/$orgSlug/ideas/$ideaId'
    | '/api/zapier/webhooks/subscribe/$id'
    | '/(authenticated)/dashboard/$orgSlug/account/'
    | '/(authenticated)/dashboard/$orgSlug/changelog/'
    | '/(authenticated)/dashboard/$orgSlug/ideas/'
    | '/(authenticated)/dashboard/$orgSlug/members/'
    | '/(authenticated)/dashboard/$orgSlug/roadmap/'
    | '/(authenticated)/dashboard/$orgSlug/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authPagesRouteRoute: typeof authPagesRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  OrgSlugRouteRoute: typeof OrgSlugRouteRouteWithChildren
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWidgetChangelogRoute: typeof ApiWidgetChangelogRoute
  ApiWidgetIdeasRoute: typeof ApiWidgetIdeasRoute
  ApiWidgetOrganizationRoute: typeof ApiWidgetOrganizationRoute
  ApiZapierWebhooksSubscribeRoute: typeof ApiZapierWebhooksSubscribeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)': {
      id: '/(auth-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)/signup': {
      id: '/(auth-pages)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authPagesSignupRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/login': {
      id: '/(auth-pages)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/org/$slug': {
      id: '/org/$slug'
      path: '/org/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof OrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/org/$slug/': {
      id: '/org/$slug/'
      path: '/'
      fullPath: '/org/$slug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/': {
      id: '/(authenticated)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedDashboardIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/org/$slug/roadmap': {
      id: '/org/$slug/roadmap'
      path: '/roadmap'
      fullPath: '/org/$slug/roadmap'
      preLoaderRoute: typeof OrgSlugRoadmapRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/org/$slug/changelog': {
      id: '/org/$slug/changelog'
      path: '/changelog'
      fullPath: '/org/$slug/changelog'
      preLoaderRoute: typeof OrgSlugChangelogRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/org/$slug/$ideaId': {
      id: '/org/$slug/$ideaId'
      path: '/$ideaId'
      fullPath: '/org/$slug/$ideaId'
      preLoaderRoute: typeof OrgSlugIdeaIdRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/api/widget/organization': {
      id: '/api/widget/organization'
      path: '/api/widget/organization'
      fullPath: '/api/widget/organization'
      preLoaderRoute: typeof ApiWidgetOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widget/ideas': {
      id: '/api/widget/ideas'
      path: '/api/widget/ideas'
      fullPath: '/api/widget/ideas'
      preLoaderRoute: typeof ApiWidgetIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widget/changelog': {
      id: '/api/widget/changelog'
      path: '/api/widget/changelog'
      fullPath: '/api/widget/changelog'
      preLoaderRoute: typeof ApiWidgetChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard/$orgSlug': {
      id: '/(authenticated)/dashboard/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/dashboard/$orgSlug'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugRouteRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/': {
      id: '/(authenticated)/dashboard/$orgSlug/'
      path: '/'
      fullPath: '/dashboard/$orgSlug/'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugIndexRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/api/zapier/webhooks/subscribe': {
      id: '/api/zapier/webhooks/subscribe'
      path: '/api/zapier/webhooks/subscribe'
      fullPath: '/api/zapier/webhooks/subscribe'
      preLoaderRoute: typeof ApiZapierWebhooksSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard/$orgSlug/settings/': {
      id: '/(authenticated)/dashboard/$orgSlug/settings/'
      path: '/settings'
      fullPath: '/dashboard/$orgSlug/settings'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugSettingsIndexRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/roadmap/': {
      id: '/(authenticated)/dashboard/$orgSlug/roadmap/'
      path: '/roadmap'
      fullPath: '/dashboard/$orgSlug/roadmap'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugRoadmapIndexRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/members/': {
      id: '/(authenticated)/dashboard/$orgSlug/members/'
      path: '/members'
      fullPath: '/dashboard/$orgSlug/members'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugMembersIndexRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/ideas/': {
      id: '/(authenticated)/dashboard/$orgSlug/ideas/'
      path: '/ideas'
      fullPath: '/dashboard/$orgSlug/ideas'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugIdeasIndexRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/changelog/': {
      id: '/(authenticated)/dashboard/$orgSlug/changelog/'
      path: '/changelog'
      fullPath: '/dashboard/$orgSlug/changelog'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugChangelogIndexRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/account/': {
      id: '/(authenticated)/dashboard/$orgSlug/account/'
      path: '/account'
      fullPath: '/dashboard/$orgSlug/account'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugAccountIndexRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/api/zapier/webhooks/subscribe/$id': {
      id: '/api/zapier/webhooks/subscribe/$id'
      path: '/$id'
      fullPath: '/api/zapier/webhooks/subscribe/$id'
      preLoaderRoute: typeof ApiZapierWebhooksSubscribeIdRouteImport
      parentRoute: typeof ApiZapierWebhooksSubscribeRoute
    }
    '/(authenticated)/dashboard/$orgSlug/ideas/$ideaId': {
      id: '/(authenticated)/dashboard/$orgSlug/ideas/$ideaId'
      path: '/ideas/$ideaId'
      fullPath: '/dashboard/$orgSlug/ideas/$ideaId'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugIdeasIdeaIdRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/changelog/new': {
      id: '/(authenticated)/dashboard/$orgSlug/changelog/new'
      path: '/changelog/new'
      fullPath: '/dashboard/$orgSlug/changelog/new'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugChangelogNewRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/$orgSlug/changelog/$changelogId': {
      id: '/(authenticated)/dashboard/$orgSlug/changelog/$changelogId'
      path: '/changelog/$changelogId'
      fullPath: '/dashboard/$orgSlug/changelog/$changelogId'
      preLoaderRoute: typeof authenticatedDashboardOrgSlugChangelogChangelogIdRouteImport
      parentRoute: typeof authenticatedDashboardOrgSlugRouteRoute
    }
  }
}

interface authPagesRouteRouteChildren {
  authPagesLoginRoute: typeof authPagesLoginRoute
  authPagesSignupRoute: typeof authPagesSignupRoute
}

const authPagesRouteRouteChildren: authPagesRouteRouteChildren = {
  authPagesLoginRoute: authPagesLoginRoute,
  authPagesSignupRoute: authPagesSignupRoute,
}

const authPagesRouteRouteWithChildren = authPagesRouteRoute._addFileChildren(
  authPagesRouteRouteChildren,
)

interface authenticatedDashboardOrgSlugRouteRouteChildren {
  authenticatedDashboardOrgSlugIndexRoute: typeof authenticatedDashboardOrgSlugIndexRoute
  authenticatedDashboardOrgSlugChangelogChangelogIdRoute: typeof authenticatedDashboardOrgSlugChangelogChangelogIdRoute
  authenticatedDashboardOrgSlugChangelogNewRoute: typeof authenticatedDashboardOrgSlugChangelogNewRoute
  authenticatedDashboardOrgSlugIdeasIdeaIdRoute: typeof authenticatedDashboardOrgSlugIdeasIdeaIdRoute
  authenticatedDashboardOrgSlugAccountIndexRoute: typeof authenticatedDashboardOrgSlugAccountIndexRoute
  authenticatedDashboardOrgSlugChangelogIndexRoute: typeof authenticatedDashboardOrgSlugChangelogIndexRoute
  authenticatedDashboardOrgSlugIdeasIndexRoute: typeof authenticatedDashboardOrgSlugIdeasIndexRoute
  authenticatedDashboardOrgSlugMembersIndexRoute: typeof authenticatedDashboardOrgSlugMembersIndexRoute
  authenticatedDashboardOrgSlugRoadmapIndexRoute: typeof authenticatedDashboardOrgSlugRoadmapIndexRoute
  authenticatedDashboardOrgSlugSettingsIndexRoute: typeof authenticatedDashboardOrgSlugSettingsIndexRoute
}

const authenticatedDashboardOrgSlugRouteRouteChildren: authenticatedDashboardOrgSlugRouteRouteChildren =
  {
    authenticatedDashboardOrgSlugIndexRoute:
      authenticatedDashboardOrgSlugIndexRoute,
    authenticatedDashboardOrgSlugChangelogChangelogIdRoute:
      authenticatedDashboardOrgSlugChangelogChangelogIdRoute,
    authenticatedDashboardOrgSlugChangelogNewRoute:
      authenticatedDashboardOrgSlugChangelogNewRoute,
    authenticatedDashboardOrgSlugIdeasIdeaIdRoute:
      authenticatedDashboardOrgSlugIdeasIdeaIdRoute,
    authenticatedDashboardOrgSlugAccountIndexRoute:
      authenticatedDashboardOrgSlugAccountIndexRoute,
    authenticatedDashboardOrgSlugChangelogIndexRoute:
      authenticatedDashboardOrgSlugChangelogIndexRoute,
    authenticatedDashboardOrgSlugIdeasIndexRoute:
      authenticatedDashboardOrgSlugIdeasIndexRoute,
    authenticatedDashboardOrgSlugMembersIndexRoute:
      authenticatedDashboardOrgSlugMembersIndexRoute,
    authenticatedDashboardOrgSlugRoadmapIndexRoute:
      authenticatedDashboardOrgSlugRoadmapIndexRoute,
    authenticatedDashboardOrgSlugSettingsIndexRoute:
      authenticatedDashboardOrgSlugSettingsIndexRoute,
  }

const authenticatedDashboardOrgSlugRouteRouteWithChildren =
  authenticatedDashboardOrgSlugRouteRoute._addFileChildren(
    authenticatedDashboardOrgSlugRouteRouteChildren,
  )

interface authenticatedDashboardRouteRouteChildren {
  authenticatedDashboardOrgSlugRouteRoute: typeof authenticatedDashboardOrgSlugRouteRouteWithChildren
  authenticatedDashboardIndexRoute: typeof authenticatedDashboardIndexRoute
}

const authenticatedDashboardRouteRouteChildren: authenticatedDashboardRouteRouteChildren =
  {
    authenticatedDashboardOrgSlugRouteRoute:
      authenticatedDashboardOrgSlugRouteRouteWithChildren,
    authenticatedDashboardIndexRoute: authenticatedDashboardIndexRoute,
  }

const authenticatedDashboardRouteRouteWithChildren =
  authenticatedDashboardRouteRoute._addFileChildren(
    authenticatedDashboardRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedDashboardRouteRoute: typeof authenticatedDashboardRouteRouteWithChildren
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardRouteRoute:
    authenticatedDashboardRouteRouteWithChildren,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface OrgSlugRouteRouteChildren {
  OrgSlugIdeaIdRoute: typeof OrgSlugIdeaIdRoute
  OrgSlugChangelogRoute: typeof OrgSlugChangelogRoute
  OrgSlugRoadmapRoute: typeof OrgSlugRoadmapRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
}

const OrgSlugRouteRouteChildren: OrgSlugRouteRouteChildren = {
  OrgSlugIdeaIdRoute: OrgSlugIdeaIdRoute,
  OrgSlugChangelogRoute: OrgSlugChangelogRoute,
  OrgSlugRoadmapRoute: OrgSlugRoadmapRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
}

const OrgSlugRouteRouteWithChildren = OrgSlugRouteRoute._addFileChildren(
  OrgSlugRouteRouteChildren,
)

interface ApiZapierWebhooksSubscribeRouteChildren {
  ApiZapierWebhooksSubscribeIdRoute: typeof ApiZapierWebhooksSubscribeIdRoute
}

const ApiZapierWebhooksSubscribeRouteChildren: ApiZapierWebhooksSubscribeRouteChildren =
  {
    ApiZapierWebhooksSubscribeIdRoute: ApiZapierWebhooksSubscribeIdRoute,
  }

const ApiZapierWebhooksSubscribeRouteWithChildren =
  ApiZapierWebhooksSubscribeRoute._addFileChildren(
    ApiZapierWebhooksSubscribeRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authPagesRouteRoute: authPagesRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  OrgSlugRouteRoute: OrgSlugRouteRouteWithChildren,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWidgetChangelogRoute: ApiWidgetChangelogRoute,
  ApiWidgetIdeasRoute: ApiWidgetIdeasRoute,
  ApiWidgetOrganizationRoute: ApiWidgetOrganizationRoute,
  ApiZapierWebhooksSubscribeRoute: ApiZapierWebhooksSubscribeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
