/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authPagesRouteRouteImport } from './routes/(auth-pages)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesSsoRouteImport } from './routes/examples/sso'
import { Route as authPagesSignupRouteImport } from './routes/(auth-pages)/signup'
import { Route as authPagesLoginRouteImport } from './routes/(auth-pages)/login'
import { Route as OrgSlugRouteRouteImport } from './routes/org/$slug/route'
import { Route as authenticatedDashboardRouteRouteImport } from './routes/(authenticated)/dashboard/route'
import { Route as OrgSlugIndexRouteImport } from './routes/org/$slug/index'
import { Route as authenticatedDashboardIndexRouteImport } from './routes/(authenticated)/dashboard/index'
import { Route as OrgSlugRoadmapRouteImport } from './routes/org/$slug/roadmap'
import { Route as OrgSlugIdeaIdRouteImport } from './routes/org/$slug/$ideaId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatedDashboardSettingsIndexRouteImport } from './routes/(authenticated)/dashboard/settings/index'
import { Route as authenticatedDashboardRoadmapIndexRouteImport } from './routes/(authenticated)/dashboard/roadmap/index'
import { Route as authenticatedDashboardMembersIndexRouteImport } from './routes/(authenticated)/dashboard/members/index'
import { Route as authenticatedDashboardIdeasIndexRouteImport } from './routes/(authenticated)/dashboard/ideas/index'
import { Route as authenticatedDashboardIdeasIdeaIdRouteImport } from './routes/(authenticated)/dashboard/ideas/$ideaId'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesRouteRoute = authPagesRouteRouteImport.update({
  id: '/(auth-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSsoRoute = ExamplesSsoRouteImport.update({
  id: '/examples/sso',
  path: '/examples/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesSignupRoute = authPagesSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const OrgSlugRouteRoute = OrgSlugRouteRouteImport.update({
  id: '/org/$slug',
  path: '/org/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedDashboardRouteRoute =
  authenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const authenticatedDashboardIndexRoute =
  authenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const OrgSlugRoadmapRoute = OrgSlugRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugIdeaIdRoute = OrgSlugIdeaIdRouteImport.update({
  id: '/$ideaId',
  path: '/$ideaId',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedDashboardSettingsIndexRoute =
  authenticatedDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardRoadmapIndexRoute =
  authenticatedDashboardRoadmapIndexRouteImport.update({
    id: '/roadmap/',
    path: '/roadmap/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardMembersIndexRoute =
  authenticatedDashboardMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardIdeasIndexRoute =
  authenticatedDashboardIdeasIndexRouteImport.update({
    id: '/ideas/',
    path: '/ideas/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardIdeasIdeaIdRoute =
  authenticatedDashboardIdeasIdeaIdRouteImport.update({
    id: '/ideas/$ideaId',
    path: '/ideas/$ideaId',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/org/$slug': typeof OrgSlugRouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/examples/sso': typeof ExamplesSsoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/org/$slug/$ideaId': typeof OrgSlugIdeaIdRoute
  '/org/$slug/roadmap': typeof OrgSlugRoadmapRoute
  '/dashboard/': typeof authenticatedDashboardIndexRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/dashboard/ideas/$ideaId': typeof authenticatedDashboardIdeasIdeaIdRoute
  '/dashboard/ideas': typeof authenticatedDashboardIdeasIndexRoute
  '/dashboard/members': typeof authenticatedDashboardMembersIndexRoute
  '/dashboard/roadmap': typeof authenticatedDashboardRoadmapIndexRoute
  '/dashboard/settings': typeof authenticatedDashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/examples/sso': typeof ExamplesSsoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/org/$slug/$ideaId': typeof OrgSlugIdeaIdRoute
  '/org/$slug/roadmap': typeof OrgSlugRoadmapRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
  '/org/$slug': typeof OrgSlugIndexRoute
  '/dashboard/ideas/$ideaId': typeof authenticatedDashboardIdeasIdeaIdRoute
  '/dashboard/ideas': typeof authenticatedDashboardIdeasIndexRoute
  '/dashboard/members': typeof authenticatedDashboardMembersIndexRoute
  '/dashboard/roadmap': typeof authenticatedDashboardRoadmapIndexRoute
  '/dashboard/settings': typeof authenticatedDashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth-pages)': typeof authPagesRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/org/$slug': typeof OrgSlugRouteRouteWithChildren
  '/(auth-pages)/login': typeof authPagesLoginRoute
  '/(auth-pages)/signup': typeof authPagesSignupRoute
  '/examples/sso': typeof ExamplesSsoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/org/$slug/$ideaId': typeof OrgSlugIdeaIdRoute
  '/org/$slug/roadmap': typeof OrgSlugRoadmapRoute
  '/(authenticated)/dashboard/': typeof authenticatedDashboardIndexRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/(authenticated)/dashboard/ideas/$ideaId': typeof authenticatedDashboardIdeasIdeaIdRoute
  '/(authenticated)/dashboard/ideas/': typeof authenticatedDashboardIdeasIndexRoute
  '/(authenticated)/dashboard/members/': typeof authenticatedDashboardMembersIndexRoute
  '/(authenticated)/dashboard/roadmap/': typeof authenticatedDashboardRoadmapIndexRoute
  '/(authenticated)/dashboard/settings/': typeof authenticatedDashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/org/$slug'
    | '/login'
    | '/signup'
    | '/examples/sso'
    | '/api/auth/$'
    | '/org/$slug/$ideaId'
    | '/org/$slug/roadmap'
    | '/dashboard/'
    | '/org/$slug/'
    | '/dashboard/ideas/$ideaId'
    | '/dashboard/ideas'
    | '/dashboard/members'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/examples/sso'
    | '/api/auth/$'
    | '/org/$slug/$ideaId'
    | '/org/$slug/roadmap'
    | '/dashboard'
    | '/org/$slug'
    | '/dashboard/ideas/$ideaId'
    | '/dashboard/ideas'
    | '/dashboard/members'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/(auth-pages)'
    | '/(authenticated)'
    | '/(authenticated)/dashboard'
    | '/org/$slug'
    | '/(auth-pages)/login'
    | '/(auth-pages)/signup'
    | '/examples/sso'
    | '/api/auth/$'
    | '/org/$slug/$ideaId'
    | '/org/$slug/roadmap'
    | '/(authenticated)/dashboard/'
    | '/org/$slug/'
    | '/(authenticated)/dashboard/ideas/$ideaId'
    | '/(authenticated)/dashboard/ideas/'
    | '/(authenticated)/dashboard/members/'
    | '/(authenticated)/dashboard/roadmap/'
    | '/(authenticated)/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authPagesRouteRoute: typeof authPagesRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  OrgSlugRouteRoute: typeof OrgSlugRouteRouteWithChildren
  ExamplesSsoRoute: typeof ExamplesSsoRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)': {
      id: '/(auth-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/sso': {
      id: '/examples/sso'
      path: '/examples/sso'
      fullPath: '/examples/sso'
      preLoaderRoute: typeof ExamplesSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)/signup': {
      id: '/(auth-pages)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authPagesSignupRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/login': {
      id: '/(auth-pages)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/org/$slug': {
      id: '/org/$slug'
      path: '/org/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof OrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/org/$slug/': {
      id: '/org/$slug/'
      path: '/'
      fullPath: '/org/$slug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/(authenticated)/dashboard/': {
      id: '/(authenticated)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedDashboardIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/org/$slug/roadmap': {
      id: '/org/$slug/roadmap'
      path: '/roadmap'
      fullPath: '/org/$slug/roadmap'
      preLoaderRoute: typeof OrgSlugRoadmapRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/org/$slug/$ideaId': {
      id: '/org/$slug/$ideaId'
      path: '/$ideaId'
      fullPath: '/org/$slug/$ideaId'
      preLoaderRoute: typeof OrgSlugIdeaIdRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard/settings/': {
      id: '/(authenticated)/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof authenticatedDashboardSettingsIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/roadmap/': {
      id: '/(authenticated)/dashboard/roadmap/'
      path: '/roadmap'
      fullPath: '/dashboard/roadmap'
      preLoaderRoute: typeof authenticatedDashboardRoadmapIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/members/': {
      id: '/(authenticated)/dashboard/members/'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof authenticatedDashboardMembersIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/ideas/': {
      id: '/(authenticated)/dashboard/ideas/'
      path: '/ideas'
      fullPath: '/dashboard/ideas'
      preLoaderRoute: typeof authenticatedDashboardIdeasIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/ideas/$ideaId': {
      id: '/(authenticated)/dashboard/ideas/$ideaId'
      path: '/ideas/$ideaId'
      fullPath: '/dashboard/ideas/$ideaId'
      preLoaderRoute: typeof authenticatedDashboardIdeasIdeaIdRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
  }
}

interface authPagesRouteRouteChildren {
  authPagesLoginRoute: typeof authPagesLoginRoute
  authPagesSignupRoute: typeof authPagesSignupRoute
}

const authPagesRouteRouteChildren: authPagesRouteRouteChildren = {
  authPagesLoginRoute: authPagesLoginRoute,
  authPagesSignupRoute: authPagesSignupRoute,
}

const authPagesRouteRouteWithChildren = authPagesRouteRoute._addFileChildren(
  authPagesRouteRouteChildren,
)

interface authenticatedDashboardRouteRouteChildren {
  authenticatedDashboardIndexRoute: typeof authenticatedDashboardIndexRoute
  authenticatedDashboardIdeasIdeaIdRoute: typeof authenticatedDashboardIdeasIdeaIdRoute
  authenticatedDashboardIdeasIndexRoute: typeof authenticatedDashboardIdeasIndexRoute
  authenticatedDashboardMembersIndexRoute: typeof authenticatedDashboardMembersIndexRoute
  authenticatedDashboardRoadmapIndexRoute: typeof authenticatedDashboardRoadmapIndexRoute
  authenticatedDashboardSettingsIndexRoute: typeof authenticatedDashboardSettingsIndexRoute
}

const authenticatedDashboardRouteRouteChildren: authenticatedDashboardRouteRouteChildren =
  {
    authenticatedDashboardIndexRoute: authenticatedDashboardIndexRoute,
    authenticatedDashboardIdeasIdeaIdRoute:
      authenticatedDashboardIdeasIdeaIdRoute,
    authenticatedDashboardIdeasIndexRoute:
      authenticatedDashboardIdeasIndexRoute,
    authenticatedDashboardMembersIndexRoute:
      authenticatedDashboardMembersIndexRoute,
    authenticatedDashboardRoadmapIndexRoute:
      authenticatedDashboardRoadmapIndexRoute,
    authenticatedDashboardSettingsIndexRoute:
      authenticatedDashboardSettingsIndexRoute,
  }

const authenticatedDashboardRouteRouteWithChildren =
  authenticatedDashboardRouteRoute._addFileChildren(
    authenticatedDashboardRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedDashboardRouteRoute: typeof authenticatedDashboardRouteRouteWithChildren
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardRouteRoute:
    authenticatedDashboardRouteRouteWithChildren,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface OrgSlugRouteRouteChildren {
  OrgSlugIdeaIdRoute: typeof OrgSlugIdeaIdRoute
  OrgSlugRoadmapRoute: typeof OrgSlugRoadmapRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
}

const OrgSlugRouteRouteChildren: OrgSlugRouteRouteChildren = {
  OrgSlugIdeaIdRoute: OrgSlugIdeaIdRoute,
  OrgSlugRoadmapRoute: OrgSlugRoadmapRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
}

const OrgSlugRouteRouteWithChildren = OrgSlugRouteRoute._addFileChildren(
  OrgSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authPagesRouteRoute: authPagesRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  OrgSlugRouteRoute: OrgSlugRouteRouteWithChildren,
  ExamplesSsoRoute: ExamplesSsoRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
